name: NeverLag
version: Kat1.0
authors: [MrKitty_Cat, borao]
main: me.camdenorrb.neverlag.NeverLag

depend: [ClearLag]

commands:

  nl:
    usage: "/nl"
    permission: "nl.lag"
    permission-message: "You don't have <permission>"